; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = 
	-DBOARD_HAS_PSRAM=0
lib_deps = 
	mbed-seeed/PN532@0.0.0+sha.85bfede025da
	bblanchon/ArduinoJson@^6.21.3
	https://github.com/mathieucarbou/ESPAsyncWebServer.git#v3.3.15
	mobizt/Firebase Arduino Client Library for ESP8266 and ESP32@^4.4.17
monitor_speed = 115200
