type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  organizationName: String
}

type RFIDDevice @table {
  deviceID: String!
  deviceType: String! # e.g., 'reader', 'tag'
  createdAt: Timestamp!
  name: String
  description: String
  lastReportedLocation: String # Consider a more structured type if needed
  lastReportedAt: Timestamp
}

type Asset @table {
  name: String!
  assetType: String!
  createdAt: Timestamp!
  description: String
  serialNumber: String
  purchaseDate: Date
}

type AssetRFIDTag @table {
  asset: Asset!
  rfidTagDevice: RFIDDevice!
  assignedAt: Timestamp!
}

type LocationHistory @table {
  assetRFIDTag: AssetRFIDTag!
  readerDevice: RFIDDevice! # The RFIDDevice that detected the tag
  timestamp: Timestamp!
  latitude: Float!
  longitude: Float!
  notes: String
}